USE [Poker]
GO

DROP TABLE IF EXISTS [dbo].[T_CRank]
;

CREATE TABLE [dbo].[T_CRank](
	[C1] tinyint NOT NULL,
	[C2] tinyint NOT NULL,
	[C3] tinyint NOT NULL,
	[C4] tinyint NOT NULL,
	[C5] tinyint NOT NULL,
    [R] int NOT NULL,
	[STR] VARCHAR(255) NOT NULL,
	BITMASK BIGINT,
	BITMASK_STR VARCHAR(64),
	CONSTRAINT PK_T_CRank PRIMARY KEY CLUSTERED (C1,C2,C3,C4,C5)
) ON [PRIMARY]
GO

UPDATE [dbo].[T_CRank]
   SET BITMASK = POWER(CAST(2 AS BIGINT),[C1]) | POWER(CAST(2 AS BIGINT),[C2]) | POWER(CAST(2 AS BIGINT),[C3]) | POWER(CAST(2 AS BIGINT),[C4]) | POWER(CAST(2 AS BIGINT),[C5])
;
     
UPDATE [dbo].[T_CRank]
   SET BITMASK_STR = [dbo].[fc_bigint_to_binary]([BITMASK])
;   
--ALTER TABLE [dbo].[T_CRank] ADD BITMASK BIGINT;
--ALTER TABLE [dbo].[T_CRank] ADD BITMASK_STR VARCHAR(64);

